### ISSUE TITLE
Can you bump ring?

### ISSUE THREAD

**Issue by svenstaro** [ThinkAlexandria/BoringAuth#5]
Since commits are slow right now, how about a ring 0.15 and then afterwards a ring 0.16 release so that people using web frameworks which also depend on ring have a chance to use BoringAuth?

Would be cool. :)

**Comment by YetAnotherMinion** [comment]
Yes. I’ll update after work today.

**Comment by YetAnotherMinion** [comment]
Released 0.9.0 which compiles with both ring 0.15 and ring 0.16
